[project]
name = "samnerf"
version = "0.1.1"



[tool.setuptools.packages.find]
include = ["samnerf*"]

[project.entry-points.'nerfstudio.method_configs']
samnerf = 'samnerf.samnerf_config:samnerf_method'
