[project]
name = "samnerf_v2"
version = "0.1.1"



[tool.setuptools.packages.find]
include = ["samnerf_v2*"]

[project.entry-points.'nerfstudio.method_configs']
samnerf_v2 = 'samnerf_v2.samnerf_config:samnerf_method'
